spring:
  # 配置RabbitMq
  rabbitmq:
    host: 192.168.119.131
    port: 5672
    username: fake-news
    password: fake-news
    virtual-host: /news
  #配置数据源
  datasource:
    #默认配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ，news?serverTimezone=GMT%2B8
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    #初始化连接数量
    initialSize: 5
    #最小空闲连接
    minIdle: 5
    #最大并发连接数
    maxActive: 20
    #超时等待时间以毫秒为单位
    maxWait: 60000
    #校验连接池中限制时间超过minEvictableIdleTimeMillis的连接对象
    timeBetweenEvictionRunsMillis: 60000
    #连接在池中保持空闲而不被空闲连接回收器线程(如果有)回收的最小时间值，单位毫秒
    minEvictableIdleTimeMillis: 300000
    #SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前
    validationQuery: SELECT 1 FROM DUAL
    #指明连接是否被空闲连接回收器(如果有)进行检验.
    #如果检测失败,则连接将被从池中去除.
    testWhileIdle: true
    #指明是否在从池中取出连接前进行检验,如果检验失败,
    #则从池中去除连接并尝试取出另一个
    testOnBorrow: false
    #指明是否在归还到池中前进行检验
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计， wall用于防火墙
    filters: stat,wall,log4j
    #poolPreparedStatements=true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  #设置别名
  type-aliases-package: com.zm.news.entity
  mapper-locations: classpath:mapper/*.xml
  #ָ指定myBatis的核心配置文件与Mapper映射文件
  configuration:
    #配置下划线转驼峰
    map-underscore-to-camel-case: true
    #是否使用缓存
    cache-enabled: true
    #是否开启延时加载
    lazy-loading-enabled: true
    #是否按需加载
    aggressive-lazy-loading: false

#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


logging:
  level:
    root: info
    com.zm.news: debug
  file:
    path: log/news-dev.log